//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDynamicAuthenticationFilter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestAuthorizationEntities : DbContext
    {
        public TestAuthorizationEntities()
            : base("name=TestAuthorizationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TRole> TRoles { get; set; }
        public virtual DbSet<TUser> TUsers { get; set; }
        public virtual DbSet<TView> TViews { get; set; }
        public virtual DbSet<TViewAccess> TViewAccesses { get; set; }
    }
}
