//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDynamicAuthenticationFilter
{
    using System;
    using System.Collections.Generic;
    
    public partial class TViewAccess
    {
        public int Id { get; set; }
        public int IdView { get; set; }
        public int IdRole { get; set; }
        public int AccessRight { get; set; }
    
        public virtual TRole TRole { get; set; }
        public virtual TView TView { get; set; }
    }
}
